"""empty message

Revision ID: b8f921d34002
Revises: e449258a1558
Create Date: 2022-05-01 13:28:50.182219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f921d34002'
down_revision = 'e449258a1558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_image_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_image_id', sa.Integer(), nullable=True),
    sa.Column('tag_name', sa.String(), nullable=True),
    sa.Column('creat_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_image_id'], ['user_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_image_tag')
    # ### end Alembic commands ###
